steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build:refs"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["emulator:exec", "\"npm run test\""]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build:production"]
  - name: node:10.15.1
    entrypoint: npm
    dir: "functions"
    args: ["install"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project", "$_FIREBASE_PROJECT_ID", "--token", "$_FIREBASE_TOKEN"]
