steps:
  - name: node:10.18.0
    args: ["node", "./scripts/install"]
  - name: node:10.18.0
    entrypoint: npm
    args: ["run", "build:refs"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    entrypoint: npm
    args: ["run", "test:cloudbuild"]
  - name: node:10.18.0
    entrypoint: npm
    args: ["run", "build:production"]
  - name: "gcr.io/$PROJECT_ID/builder"
    entrypoint: bash
    args:
      [
        "-c",
        "bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X fix",
      ]
    env:
      - "VCS_COMMIT_ID=$COMMIT_SHA"
      - "VCS_BRANCH_NAME=$BRANCH_NAME"
      - "VCS_PULL_REQUEST=$_PR_NUMBER"
      - "CI_BUILD_ID=$BUILD_ID"
      - "CODECOV_TOKEN=$_CODECOV_TOKEN"
  - name: node:10.18.0
    entrypoint: npm
    dir: "functions"
    args: ["ci"]
  - name: node:10.18.0
    entrypoint: npm
    dir: "functions"
    args: ["run", "build"]
timeout: 900s
