steps:
  - name: node:10.18.0
    entrypoint: npm
    args: ["ci"]
  - name: node:10.18.0
    entrypoint: npm
    args: ["run", "build:refs"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    entrypoint: npm
    args: ["run", "test:emulator"]
  - name: node:10.18.0
    entrypoint: npm
    args: ["run", "build:production"]
    env:
      - 'FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
  - name: node:10.18.0
    entrypoint: npm
    dir: "functions"
    args: ["ci"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project", "$_FIREBASE_PROJECT_ID", "--token", "$_FIREBASE_TOKEN"]
timeout: 900s
