steps:
  - name: node:12.13.1
    entrypoint: npm
    args: ["ci"]
  - name: node:12.13.1
    entrypoint: npm
    args: ["run", "build:refs"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    entrypoint: npm
    args: ["run", "test:cloudbuild"]
  - name: node:12.13.1
    entrypoint: npm
    args: ["run", "build:production"]
  - name: "gcr.io/$PROJECT_ID/builder"
    entrypoint: bash
    args: ['-c', 'bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X fix']
    env:
    - 'VCS_COMMIT_ID=$COMMIT_SHA'
    - 'VCS_BRANCH_NAME=$BRANCH_NAME'
    - 'VCS_PULL_REQUEST=$_PR_NUMBER'
    - 'CI_BUILD_ID=$BUILD_ID'
    - 'CODECOV_TOKEN=$_CODECOV_TOKEN'
  - name: node:12.13.1
    entrypoint: npm
    dir: "functions"
    args: ["install"]
  - name: node:12.13.1
    entrypoint: npm
    dir: "functions"
    args: ["run", "build"]
