steps:
  - name: node:14
    entrypoint: npm
    args: ["ci"]
  - name: node:14
    entrypoint: npm
    args: ["run", "build:refs"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    entrypoint: npm
    args: ["run", "test:emulator"]
  - name: node:14
    entrypoint: npm
    args: ["run", "build:production"]
  - name: node:14
    entrypoint: npm
    dir: "functions"
    args: ["ci"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project", "$_FIREBASE_PROJECT_ID", "--token", "$_FIREBASE_TOKEN"]
timeout: 900s
